


String getWeatherIconRes(int weatherCode,{bool isDay = true}  ) {
  switch (weatherCode) {
    case 0:
      return isDay
          ? 'assets/images/clear_sky.png'
          : 'assets/images/clear_sky_night.png';
    case 1:
      return isDay
          ? 'assets/images/mainly_clear.png'
          : 'assets/images/mainly_clear_night.png';
    case 2:
      return isDay
          ? 'assets/images/partly_cloudy.png'
          : 'assets/images/partly_cloudy_night.png';
    case 3:
      return isDay
          ? 'assets/images/overcast.png'
          : 'assets/images/overcast_night.png';
    case 45:
      return isDay
          ? 'assets/images/fog.png'
          : 'assets/images/fog_night.png';
    case 48:
      return isDay
          ? 'assets/images/depositing_rime_fog.png'
          : 'assets/images/depositing_rime_fog_night.png';
    case 51:
      return isDay
          ? 'assets/images/drizzle_light.png'
          : 'assets/images/drizzle_light_night.png';
    case 53:
      return isDay
          ? 'assets/images/drizzle_moderate.png'
          : 'assets/images/drizzle_moderate_night.png';
    case 55:
      return isDay
          ? 'assets/images/drizzle_intensity.png'
          : 'assets/images/drizzle_intensity_night.png';
    case 56:
      return isDay
          ? 'assets/images/freezing_drizzle_light.png'
          : 'assets/images/freezing_drizzle_light_night.png';
    case 57:
      return isDay
          ? 'assets/images/freezing_drizzle_intensity.png'
          : 'assets/images/freezing_drizzle_intensity_night.png';
    case 61:
      return isDay
          ? 'assets/images/rain_slight.png'
          : 'assets/images/rain_slight_night.png';
    case 63:
      return isDay
          ? 'assets/images/rain_moderate.png'
          : 'assets/images/rain_moderate_night.png';
    case 65:
      return isDay
          ? 'assets/images/rain_intensity.png'
          : 'assets/images/rain_intensity_night.png';
    case 66:
      return isDay
          ? 'assets/images/freezing_light.png'
          : 'assets/images/freezing_light_night.png';
    case 67:
      return isDay
          ? 'assets/images/freezing_heavy.png'
          : 'assets/images/freezing_heavy_night.png';
    case 71:
      return isDay
          ? 'assets/images/rain_slight.png'
          : 'assets/images/rain_slight_night.png';
    case 73:
      return isDay
          ? 'assets/images/snow_fall_moderate.png'
          : 'assets/images/snow_fall_moderate_night.png';
    case 75:
      return isDay
          ? 'assets/images/snow_fall_intensity.png'
          : 'assets/images/snow_fall_intensity_night.png';
    case 77:
      return isDay
          ? 'assets/images/snow_grains.png'
          : 'assets/images/snow_grains_night.png';
    case 80:
      return isDay
          ? 'assets/images/rain_shower_slight.png'
          : 'assets/images/rain_shower_slight_night.png';
    case 81:
      return isDay
          ? 'assets/images/rain_shower_moderate.png'
          : 'assets/images/rain_shower_moderate_night.png';
    case 82:
      return isDay
          ? 'assets/images/snow_shower_slight.png'
          : 'assets/images/rain_shower_violent_night.png';
    case 85:
      return isDay
          ? 'assets/images/snow_shower_slight.png'
          : 'assets/images/snow_shower_slight_night.png';
    case 86:
      return isDay
          ? 'assets/images/snow_shower_heavy.png'
          : 'assets/images/snow_shower_heavy_night.png';
    case 95:
      return isDay
          ? 'assets/images/thunderstrom_slight_or_moderate.png'
          : 'assets/images/thunderstrom_slight_or_moderate_night.png';
    case 96:
      return isDay
          ? 'assets/images/thunderstrom_with_slight_hail.png'
          : 'assets/images/thunderstrom_with_slight_hail_night.png';
    case 99:
      return isDay
          ? 'assets/images/thunderstrom_with_heavy_hail.png'
          : 'assets/images/thunderstrom_with_heavy_hail_night.png';
    default:
      return 'assets/images/ic_launcher_background.png';
  }
}